spring.application.name=nursecall

spring.datasource.url=jdbc:mysql://localhost:3306/nursecall
spring.datasource.username=root
spring.datasource.password=Awas10

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

server.port=8080